# Mutations for Educational Platform

# User Mutations
mutation UpsertUser($username: String!) @auth(level: USER) {
  user_upsert(data: { id_expr: "auth.uid", username: $username })
}

mutation DeleteUser @auth(level: USER) {
    user_delete(key: {id_expr: "auth.uid"})
}

# Subject Mutations
mutation CreateSubject($name: String!, $description: String!) @auth(level: ADMIN) {
  subject_insert(data: { name: $name, description: $description })
}

mutation UpdateSubject($id: UUID!, $name: String, $description: String) @auth(level: ADMIN) {
  subject_update(key: { id: $id }, data: { name: $name, description: $description })
}

mutation DeleteSubject($id: UUID!) @auth(level: ADMIN) {
  subject_delete(key: { id: $id })
}

# Video Mutations
mutation CreateVideo($subjectId: UUID!, $title: String!, $url: String!, $description: String) @auth(level: ADMIN) {
  video_insert(data: { subjectId: $subjectId, title: $title, url: $url, description: $description })
}
